### ISSUE TITLE
Impostazione generale

### ISSUE THREAD

**Issue by amos783** [sonoluigi/dante#2]
Immagino il sito come un aggregatore di link utili allo studio. Cosa serve per lo studio di Dante?

1. I testi delle opere: https://www.danteonline.it/opere/
2. Video (bene quelli di Barbero), aggiungerei il canale La Divina Commedia in HD e qualche video di Serianni (magari facciamo una issue solo per i video)
3. Immagini
4. Commenti alla Commedia: https://dante.dartmouth.edu/
5. Altri siti di interesse

Se siete d'accordo iniziamo a rifletterci questa settimana.
Il 25 marzo è il Dantedì

**Comment by sonoluigi** [comment]
Salve prof, il canale _La Divina Commedia in HD_ è già presente nella sezione video, ma abbiamo sbagliato a rinominarlo, mentre il sito del _DanteProject_ di Darthmouth è già presente nella sezione _Link Utili_. Provvederemo ad inserire anche le altre risorse da lei citate, ma ne parleremo comunque in classe in maniera tale da accogliere anche altri consigli.

**Comment by sonoluigi** [comment]
Salve prof, abbiamo applicato tutti i suoi suggerimenti al sito, eccezion fatta per le immagini, poiché tutti i siti con immagini stock sono a pagamento. Se per lei va bene posso marcare questa Issue come risolta.
